# Site settings
name: Yunus YILDIRIM
description: "Kişisel Web Sayfası"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  Th3GundY
facebook_username: Th3GundY
twitter_username: Th3GundY
google_plus_username: 107077406348383283812
linkedin_username: yunusyildirim
blog_url: "https://yunusyildirim.blogspot.com"
email: info@yildirimyunus.com


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars3.githubusercontent.com/u/6793697?v=3&s=460"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/heckirBoy.jpg"
#favicon_img_path: "imgs/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
